# Generated by Django 3.1.4 on 2020-12-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201211_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Echo',
            new_name='Echos',
        ),
    ]
