# Generated by Django 3.1.4 on 2020-12-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201211_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Echos',
            new_name='Echo',
        ),
    ]
